const storyTypes = {
	ADD_NEW_STORY_START: "ADD_NEW_STORY_START",
	FETCH_STORIES_START: "FETCH_STORIES_START",
	SET_STORIES: "SET_STORIES",
	DELETE_STORY_START: "DELETE_STORY_START",
	FETCH_STORY_START: "FETCH_STORY_START",
	SET_STORY: "SET_STORY",
	FETCH_USER_STORIES_START: "FETCH_STORIES_START",
	ADD_NEW_COMMENT_START: "ADD_NEW_COMMENT_START"
};

export default storyTypes;
